# Site settings
title: "The Stable - Camper Adventures"
description: "Guided group adventures with our fleet of 10 campervans"
baseurl: ""
url: "https://trips.thestable.bg"

# Logo settings
logo: "assets/images/logo/logo.svg"

# Analytics
google_analytics: G-4ZJF48SWW2

# Contact Information
contact:
  email: trips@thestable.bg
  phone: "+359888820589"
  address: "bul. Cherni Vrah 84, Sofia, Bulgaria"

# Social Media
social:
  facebook: "https://www.facebook.com/thestablevans"
  instagram: "https://www.instagram.com/thestablevans"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  trips:
    output: true
    permalink: /trips/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "trips"
    values:
      layout: "trip"

# Exclude from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - src/
  - Gemfile
  - Gemfile.lock
  - vendor/
